/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StudentInfo = IDL.Record({
  'age' : IDL.Nat,
  'stream' : IDL.Text,
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'grade' : IDL.Text,
});
export const QuizAnswer = IDL.Record({
  'categoryName' : IDL.Text,
  'question' : IDL.Text,
  'selectedAnswer' : IDL.Opt(IDL.Text),
});
export const QuizResponse = IDL.Record({
  'studentInfo' : StudentInfo,
  'answers' : IDL.Vec(QuizAnswer),
  'submittedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'getAllResponses' : IDL.Func([], [IDL.Vec(QuizResponse)], ['query']),
  'getTotalResponses' : IDL.Func([], [IDL.Nat], ['query']),
  'getUniqueStudentCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitResponse' : IDL.Func([StudentInfo, IDL.Vec(QuizAnswer)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StudentInfo = IDL.Record({
    'age' : IDL.Nat,
    'stream' : IDL.Text,
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'grade' : IDL.Text,
  });
  const QuizAnswer = IDL.Record({
    'categoryName' : IDL.Text,
    'question' : IDL.Text,
    'selectedAnswer' : IDL.Opt(IDL.Text),
  });
  const QuizResponse = IDL.Record({
    'studentInfo' : StudentInfo,
    'answers' : IDL.Vec(QuizAnswer),
    'submittedAt' : IDL.Int,
  });
  
  return IDL.Service({
    'getAllResponses' : IDL.Func([], [IDL.Vec(QuizResponse)], ['query']),
    'getTotalResponses' : IDL.Func([], [IDL.Nat], ['query']),
    'getUniqueStudentCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitResponse' : IDL.Func([StudentInfo, IDL.Vec(QuizAnswer)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };